Repository algo-itzy/algo-itzy, pull requests merged in 2021-09, with the labels that each got.

#6 [Solve] 21.09.09 (목) 스터디를 위한 승주의 알고리즘 풀이!
  BOJ/bfs/07569-토마토/07569-토마토-seungjoo.py
  BOJ/bfs/09019-DSLR/09019-DSLR-seungjoo.py
  BOJ/bfs/10026-적록색약/10026-적록색약-seungjoo.py
  BOJ/dp/09461-파도반_수열/09461-파도반_수열-seungjoo.py
  BOJ/greedy/11047-동전_0/11047-동전_0-seungjoo.py
  BOJ/mathematics/06064-카잉_달력/06064-카잉_달력-seungjoo.py
  BOJ/mathematics/09375-패션왕_신해빈/09375-패션왕_신해빈-seungjoo.py
  BOJ/string/05525-IOIOI/05525-IOIOI-seungjoo.py
Labels: 😀 한승주

#7 21.09.09 (yeonhee)
  BOJ/bfs/07569-토마토/07569-토마토-yeonhee.py
  BOJ/bfs/09019-DSLR/09019-DSLR-yeonhee.py
  BOJ/bfs/10026-적록색약/10026-적록색약-yeonhee.py
  BOJ/dp/09461-파도반_수열/09461-파도반_수열-yeonhee.py
  BOJ/greedy/11047-동전_0/11047-동전_0-yeonhee.py
  BOJ/mathematics/06064-카잉_달력/06064-카잉_달력-yeonhee.py
  BOJ/mathematics/09375-패션왕_신해빈/09375-패션왕_신해빈-yeonhee.py
  BOJ/string/05525-IOIOI/05525-IOIOI-yeonhee.py
Labels: 🔮 채연희

#8 09.09 Study PR (yoonbaek)
  BOJ/bfs/07569-토마토/07569-토마토-yoonbaek.py
  BOJ/bfs/09019-DSLR/09019-DSLR-yoonbaek.py
  BOJ/bfs/10026-적록색약/10026-적록색약-yoonbaek.py
  BOJ/dp/09461-파도반_수열/09461-파도반_수열-yoonbaek.py
  BOJ/greedy/11047-동전_0/11047-동전_0-yoonbaek.py
  BOJ/mathematics/06064-카잉_달력/06064-카잉_달력-yoonbaek.py
  BOJ/mathematics/09375-패션왕_신해빈/09375-패션왕_신해빈-yoonbaek.py
  BOJ/string/05525-IOIOI/05525-IOIOI-yoonbaek.py
Labels: 😀 백승윤

#5 21.09.09 (seokzin)
  BOJ/bfs/07569-토마토/07569-토마토-seokzin.py
  BOJ/bfs/09019-DSLR/09019-DSLR-seokzin.py
  BOJ/bfs/10026-적록색약/10026-적록색약-seokzin.py
  BOJ/dp/09461-파도반_수열/09461-파도반_수열-seokzin.py
  BOJ/greedy/11047-동전_0/11047-동전_0-seokzin.py
  BOJ/mathematics/06064-카잉_달력/06064-카잉_달력-seokzin.py
  BOJ/mathematics/09375-패션왕_신해빈/09375-패션왕_신해빈-seokzin.py
  BOJ/string/05525-IOIOI/05525-IOIOI-seokzin.py
Labels: 🌰 소석진

#15 21.09.16 스터디 문제풀이
  BOJ/bfs/11403-경로_찾기/11403-경로_찾기-seungjoo.py
  BOJ/bfs/16236-아기_상어/16236-아기_상어-seungjoo.py
  BOJ/bfs/16928-뱀과_사다리_게임/16928-뱀과_사다리_게임-seungjoo.py
  BOJ/dp/17626-Four_Squares/17626-Four_Squares-seungjoo.py
  BOJ/implementation/14500-테트로미노/14500-테트로미노-seungjoo.py
  BOJ/prefix_sum/11659-구간_합_구하기_4/11659-구간_합_구하기_4-seungjoo.py
  BOJ/priority_queue/11286-절댓값_힙/11286-절댓값_힙-seungjoo.py
  BOJ/set-map_by_hashing/17219-비밀번호_찾기/17219-비밀번호_찾기-seungjoo.py
Labels: 😀 한승주

#14 21.09.09 (seokzin)
  BOJ/bfs/11403-경로_찾기/11403-경로_찾기-seokzin.py
  BOJ/bfs/16928-뱀과_사다리_게임/16928-뱀과_사다리_게임-seokzin.py
  BOJ/dp/17626-Four_Squares/17626-Four_Squares-seokzin.py
  BOJ/implementation/14500-테트로미노/14500-테트로미노-seokzin.py
  BOJ/prefix_sum/11659-구간_합_구하기_4/11659-구간_합_구하기_4-seokzin.py
  BOJ/priority_queue/11286-절댓값_힙/11286-절댓값_힙-seokzin.py
  BOJ/set-map_by_hashing/17219-비밀번호_찾기/17219-비밀번호_찾기-seokzin.py
Labels: 🌰 소석진, 😥 못풀었어요

#16 21.09.16 스터디 문제풀이
  BOJ/bfs/11403-경로_찾기/11403-경로_찾기-seungkyu.py
  BOJ/bfs/16928-뱀과_사다리_게임/16928-뱀과_사다리_게임-seungkyu.py
  BOJ/dp/17626-Four_Squares/17626-Four_Squares-seungkyu.py
  BOJ/prefix_sum/11659-구간_합_구하기_4/11659-구간_합_구하기_4-seungkyu.py
  BOJ/priority_queue/11286-절댓값_힙/11286-절댓값_힙-seungkyu.py
  BOJ/set-map_by_hashing/17219-비밀번호_찾기/17219-비밀번호_찾기-seungkyu.py
Labels: :monkey_face: 김승규, 😥 못풀었어요

#17 21.09.16 (백승윤)
  BOJ/bfs/11403-경로_찾기/11403-경로_찾기-yoonbaek.py
  BOJ/bfs/16928-뱀과_사다리_게임/16928-뱀과_사다리_게임-yoonbaek.py
  BOJ/dp/17626-Four_Squares/17626-Four_Squares-yoonbaek.py
  BOJ/prefix_sum/11659-구간_합_구하기_4/11659-구간_합_구하기_4-yoonbaek.py
  BOJ/priority_queue/11286-절댓값_힙/11286-절댓값_힙-yoonbaek.py
  BOJ/set-map_by_hashing/17219-비밀번호_찾기/17219-비밀번호_찾기-yoonbaek.py
Labels: 😀 백승윤, 😥 못풀었어요

#18 test: git
  BOJ/bfs/16236-아기_상어/16236-아기_상어-jiwoong.py
  BOJ/dfs/02606-바이러스/02606-바이러스-jiwoong.py
  BOJ/set-map_by_hashing/01620-나는야_포켓몬_마스터_이다솜/01620-나는야_포켓몬_마스터_이다솜-jiwoong.py
  SWEA/queue/L5102-노드의_거리/L5102-노드의_거리-jiwoong-1.py
Labels: 😀 정지웅

#20 test: Branch test
  BOJ/bfs/16236-아기_상어/16236-아기_상어-yeonju.py
Labels: 😀 위연주

#19 test: Branch test
  BOJ/bfs/16236-아기_상어/16236-아기_상어-seokzin.py
Labels: 🌰 소석진

#27 21.09.19 (yeonju)
  BOJ/bfs/14502-연구소/14502-연구소-yeonju.py
Labels: 😀 위연주

#23 21.09.19 (seokzin)
  BOJ/bfs/14502-연구소/14502-연구소-seokzin.py
Labels: 🌰 소석진

#26 21.09.19 (yeonhee)
  BOJ/bfs/14502-연구소/14502-연구소-yeonhee.py
Labels: 🔮 채연희

#25 [Solve] 21.09.19 (일) 스터디를 위한 승주의 알고리즘 풀이!
  BOJ/bfs/14502-연구소/14502-연구소-seungjoo.py
Labels: 😀 한승주

#29 21.09.19 (yoonbaek)
  BOJ/bfs/14502-연구소/14502-연구소-yoonbaek.py
  BOJ/bruteforcing/01107-리모컨/01107-리모컨-yoonbaek.py
  BOJ/divide_and_conquer/01780-종이의_개수/01780-종이의_개수-yoonbaek.py
  BOJ/implementation/14500-테트로미노/14500-테트로미노-yoonbaek.py
  BOJ/mathematics/01978-소수_찾기/01978-소수_찾기-yoonbaek.py
Labels: 😀 백승윤

#28 21.09.19 (jiwoong)
  BOJ/bfs/14502-연구소/14502-연구소-jiwoong.py
Labels: 😀 정지웅

#32 21.09.23 (seokzin)
  README.md
  SWEA/implementation/L5185-이진수/L5185-이진수-jiwoong.py
  SWEA/implementation/L5185-이진수/L5185-이진수-seokzin.py
  SWEA/implementation/L5185-이진수/L5185-이진수-seungjoo.py
  SWEA/implementation/L5185-이진수/L5185-이진수-seungkyu.py
  SWEA/implementation/L5185-이진수/L5185-이진수-yeonhee.py
  SWEA/implementation/L5185-이진수/L5185-이진수-yeonju.py
  SWEA/implementation/L5185-이진수/L5185-이진수-yoonbaek.py
  SWEA/implementation/L5185-이진수/README.md
  SWEA/implementation/L5186-이진수2/L5186-이진수2-jiwoong.py
  SWEA/implementation/L5186-이진수2/L5186-이진수2-seokzin.py
  SWEA/implementation/L5186-이진수2/L5186-이진수2-seungjoo.py
  SWEA/implementation/L5186-이진수2/L5186-이진수2-seungkyu.py
  SWEA/implementation/L5186-이진수2/L5186-이진수2-yeonhee.py
  SWEA/implementation/L5186-이진수2/L5186-이진수2-yeonju.py
  SWEA/implementation/L5186-이진수2/L5186-이진수2-yoonbaek.py
  SWEA/implementation/L5186-이진수2/README.md
  SWEA/mkdir.py
Labels: 🌰 소석진

#34 21.09.23 (seokzin)
  BOJ/implementation/15683-감시/15683-감시-seokzin.py
  SWEA/implementation/L5185-이진수/L5185-이진수-seokzin.py
  SWEA/implementation/L5186-이진수2/L5186-이진수2-seokzin.py
Labels: 🌰 소석진

#35 21.09.23 (seungjoo)
  BOJ/implementation/15683-감시/15683-감시-seungjoo.py
  SWEA/implementation/L5185-이진수/L5185-이진수-seungjoo.py
  SWEA/implementation/L5186-이진수2/L5186-이진수2-seungjoo.py
Labels: 😀 한승주

#38 21.09.23 (yeonhee)
  BOJ/implementation/15683-감시/15683-감시-yeonhee.py
  SWEA/implementation/L5185-이진수/L5185-이진수-yeonhee.py
  SWEA/implementation/L5186-이진수2/L5186-이진수2-yeonhee.py
Labels: 🔮 채연희

#36 21.09.23 (seungkyu)
  BOJ/implementation/15683-감시/15683-감시-seungkyu.py
  SWEA/implementation/L5185-이진수/L5185-이진수-seungkyu.py
  SWEA/implementation/L5186-이진수2/L5186-이진수2-seungkyu.py
Labels: :monkey_face: 김승규

#39 21.09.23 (jiwoong)
  BOJ/implementation/15683-감시/15683-감시-jiwoong.py
  SWEA/implementation/L5185-이진수/L5185-이진수-jiwoong.py
  SWEA/implementation/L5186-이진수2/L5186-이진수2-jiwoong.py
Labels: 😀 정지웅

#40 21.09.23 (yeonju)
  BOJ/implementation/15683-감시/15683-감시-yeonju.py
  SWEA/implementation/L5185-이진수/L5185-이진수-yeonju.py
Labels: 😀 위연주, 😎 참신한풀이, 🚀효율적인풀이

#42 21.09.26 (seungjoo)
  BOJ/implementation/14499-주사위_굴리기/14499-주사위_굴리기-seungjoo.py
  SWEA/bfs/1953-탈주범_검거/1953-탈주범_검거-seungjoo.py
  SWEA/implementation/10966-물놀이를_가자/10966-물놀이를_가자-seungjoo.py
  SWEA/implementation/1949-등산로_조성/1949-등산로_조성-seungjoo.py
  SWEA/implementation/1952-수영장/1952-수영장-seungjoo.py
Labels: 😀 한승주

#47 21.09.26 (yoonbaek)
  BOJ/implementation/14499-주사위_굴리기/14499-주사위_굴리기-yoonbaek.py
  SWEA/bfs/1953-탈주범_검거/1953-탈주범_검거-yoonbaek.py
  SWEA/implementation/1949-등산로_조성/1949-등산로_조성-yoonbaek.py
  SWEA/implementation/1952-수영장/1952-수영장-yoonbaek.py
Labels: 😀 백승윤, 😥 못풀었어요

#44 21.09.26 (seokzin)
  BOJ/implementation/14499-주사위_굴리기/14499-주사위_굴리기-seokzin.py
  SWEA/bfs/1953-탈주범_검거/1953-탈주범_검거-seokzin.py
  SWEA/implementation/10966-물놀이를_가자/10966-물놀이를_가자-seokzin.py
  SWEA/implementation/1949-등산로_조성/1949-등산로_조성-seokzin.py
  SWEA/implementation/1952-수영장/1952-수영장-seokzin.py
Labels: 🌰 소석진

#43 21.09.26 (yeonhee)
  BOJ/implementation/14499-주사위_굴리기/14499-주사위_굴리기-yeonhee.py
  SWEA/bfs/1953-탈주범_검거/1953-탈주범_검거-yeonhee.py
  SWEA/implementation/10966-물놀이를_가자/10966-물놀이를_가자-yeonhee.py
  SWEA/implementation/1949-등산로_조성/1949-등산로_조성-yeonhee.py
  SWEA/implementation/1952-수영장/1952-수영장-yeonhee.py
Labels: 🔮 채연희

#46 21.09.26 (seungkyu)
  BOJ/implementation/14499-주사위_굴리기/14499-주사위_굴리기-seungkyu.py
Labels: :monkey_face: 김승규, 😥 못풀었어요

#45 21.09.26 (Jiwoong)
  BOJ/implementation/14499-주사위_굴리기/14499-주사위_굴리기-jiwoong.py
  SWEA/bfs/1953-탈주범_검거/1953-탈주범_검거-jiwoong.py
  SWEA/implementation/10966-물놀이를_가자/10966-물놀이를_가자-jiwoong.py
  SWEA/implementation/1949-등산로_조성/1949-등산로_조성-jiwoong.py
  SWEA/implementation/1952-수영장/1952-수영장-jiwoong.py
Labels: 😀 정지웅

#49 21.09.30 (seokzin)
  BOJ/implementation/15685-드래곤_커브/15685-드래곤_커브-seokzin.py
  SWEA/bruteforcing/L5188-최소합/L5188-최소합-seokzin.py
  SWEA/bruteforcing/L5189-전자카트/L5189-전자카트-seokzin.py
  SWEA/greedy/L5201-컨테이너_운반/L5201-컨테이너_운반-seokzin.py
  SWEA/greedy/L5202-화물_도크/L5202-화물_도크-seokzin.py
  SWEA/greedy/L5203-베이비진_게임/L5203-베이비진_게임-seokzin.py
Labels: 🌰 소석진

#50 21.09.30 (seungjoo)
  BOJ/implementation/15685-드래곤_커브/15685-드래곤_커브-seungjoo.py
  SWEA/bruteforcing/L5188-최소합/L5188-최소합-seungjoo.py
  SWEA/bruteforcing/L5189-전자카트/L5189-전자카트-seungjoo.py
  SWEA/greedy/L5201-컨테이너_운반/L5201-컨테이너_운반-seungjoo.py
  SWEA/greedy/L5202-화물_도크/L5202-화물_도크-seungjoo.py
  SWEA/greedy/L5203-베이비진_게임/L5203-베이비진_게임-seungjoo.py
Labels: 😀 한승주

#54 21.09.30 (seungkyu)
  BOJ/implementation/15685-드래곤_커브/15685-드래곤_커브-seungkyu.py
  SWEA/bfs/1953-탈주범_검거/1953-탈주범_검거-seungkyu.py
  SWEA/bruteforcing/L5188-최소합/L5188-최소합-seungkyu.py
  SWEA/bruteforcing/L5189-전자카트/L5189-전자카트-seungkyu.py
  SWEA/greedy/L5201-컨테이너_운반/L5201-컨테이너_운반-seungkyu.py
  SWEA/greedy/L5202-화물_도크/L5202-화물_도크-seungkyu.py
  SWEA/greedy/L5203-베이비진_게임/L5203-베이비진_게임-seungkyu.py
  SWEA/implementation/10966-물놀이를_가자/10966-물놀이를_가자-seungkyu.py
  SWEA/implementation/1949-등산로_조성/1949-등산로_조성-seungkyu.py
  SWEA/implementation/1952-수영장/1952-수영장-seungkyu.py
Labels: :monkey_face: 김승규

#52 21.09.30 (jiwoong)
  BOJ/implementation/15685-드래곤_커브/15685-드래곤_커브-jiwoong.py
  SWEA/bruteforcing/L5188-최소합/L5188-최소합-jiwoong.py
  SWEA/bruteforcing/L5189-전자카트/L5189-전자카트-jiwoong.py
  SWEA/greedy/L5201-컨테이너_운반/L5201-컨테이너_운반-jiwoong.py
  SWEA/greedy/L5202-화물_도크/L5202-화물_도크-jiwoong.py
  SWEA/greedy/L5203-베이비진_게임/L5203-베이비진_게임-jiwoong.py
Labels: 😀 정지웅

#53 21.09.30 (yeonhee)
  BOJ/implementation/15685-드래곤_커브/15685-드래곤_커브-yeonhee.py
  SWEA/bruteforcing/L5188-최소합/L5188-최소합-yeonhee.py
  SWEA/bruteforcing/L5189-전자카트/L5189-전자카트-yeonhee.py
  SWEA/greedy/L5201-컨테이너_운반/L5201-컨테이너_운반-yeonhee.py
  SWEA/greedy/L5202-화물_도크/L5202-화물_도크-yeonhee.py
  SWEA/greedy/L5203-베이비진_게임/L5203-베이비진_게임-yeonhee.py
Labels: 🔮 채연희

#51 21.09.30 (Yoonbaek)
  BOJ/implementation/15685-드래곤_커브/15685-드래곤_커브-yoonbaek.py
  SWEA/bfs/1953-탈주범_검거/1953-탈주범_검거-yoonbaek.py
  SWEA/bruteforcing/L5188-최소합/L5188-최소합-yoonbaek.py
  SWEA/bruteforcing/L5189-전자카트/L5189-전자카트-yoonbaek.py
  SWEA/greedy/L5201-컨테이너_운반/L5201-컨테이너_운반-yoonbaek.py
  SWEA/greedy/L5202-화물_도크/L5202-화물_도크-yoonbaek.py
  SWEA/greedy/L5203-베이비진_게임/L5203-베이비진_게임-yoonbaek.py
  SWEA/implementation/10966-물놀이를_가자/10966-물놀이를_가자-yoonbaek.py
Labels: 😀 백승윤
