Repository algo-itzy/algo-itzy, pull requests merged in 2021-12, with the labels that each got.

#162 21.12.02 (seungjoo)
  BOJ/dfs/01167-트리의_지름/01167-트리의_지름-seungjoo.py
  BOJ/dp/01149-RGB거리/01149-RGB거리-seungjoo.py
Labels: 😀 한승주

#158 21.12.02 (yeonhee)
  BOJ/dfs/01167-트리의_지름/01167-트리의_지름-yeonhee.py
  BOJ/dp/01149-RGB거리/01149-RGB거리-yeonhee.py
Labels: 🔮 채연희

#157 21.12.02 (seokzin)
  BOJ/dfs/01167-트리의_지름/01167-트리의_지름-seokzin.py
  BOJ/dp/01149-RGB거리/01149-RGB거리-seokzin.py
Labels: 🌰 소석진

#163 21.12.02 (yoonbaek)
  BOJ/dp/01149-RGB거리/01149-RGB거리-yoonbaek.go
Labels: 😀 백승윤

#160 21.12.02 (seungkyu)
  BOJ/dp/01149-RGB거리/01149-RGB거리-seungkyu.py
Labels: :monkey_face: 김승규

#164 21.12.02 (yoonbaek)
  BOJ/dfs/01167-트리의_지름/01167-트리의_지름-yoonbaek.go
  BOJ/dfs/01167-트리의_지름/01167-트리의_지름-yoonbaek.py
  BOJ/dp/01149-RGB거리/01149-RGB거리-yoonbaek.py
Labels: 😀 백승윤

#161 21.12.02 (yeonju)
  BOJ/dp/01149-RGB거리/01149-RGB거리-yeonju.py
  BOJ/mathematics/01629-곱셈/01629-곱셈-yeonju.py
Labels: 😀 위연주

#165 21.12.05 (seungjoo)
  BOJ/dijkstra/01753-최단경로/01753-최단경로-seungjoo.py
  BOJ/mathematics/01629-곱셈/01629-곱셈-seungjoo.py
Labels: 😀 한승주

#168 21.12.05 (yeonhee)
  BOJ/dijkstra/01753-최단경로/01753-최단경로-yeonhee.py
  BOJ/mathematics/01629-곱셈/01629-곱셈-yeonhee.py
Labels: 🔮 채연희

#166 21.12.05 (yoonbaek)
  BOJ/dijkstra/01753-최단경로/01753-최단경로-yoonbaek.go
  BOJ/dijkstra/01753-최단경로/01753-최단경로-yoonbaek.py
  BOJ/mathematics/01629-곱셈/01629-곱셈-yoonbaek.go
  BOJ/mathematics/01629-곱셈/01629-곱셈-yoonbaek.py
Labels: 😀 백승윤

#167 21.12.05 (seokzin)
  BOJ/dijkstra/01753-최단경로/01753-최단경로-seokzin.py
  BOJ/mathematics/01629-곱셈/01629-곱셈-seokzin.py
Labels: 🌰 소석진

#169 21.12.05 (seungkyu)
  BOJ/dijkstra/01753-최단경로/01753-최단경로-seungkyu.py
  BOJ/mathematics/01629-곱셈/01629-곱셈-seungkyu.py
Labels: :monkey_face: 김승규

#171 21.12.09 Problem set
  BOJ/bellman–ford/01865-웜홀/01865-웜홀-jiwoong.py
  BOJ/bellman–ford/01865-웜홀/01865-웜홀-seokzin.py
  BOJ/bellman–ford/01865-웜홀/01865-웜홀-seungjoo.py
  BOJ/bellman–ford/01865-웜홀/01865-웜홀-seungkyu.py
  BOJ/bellman–ford/01865-웜홀/01865-웜홀-yeonhee.py
  BOJ/bellman–ford/01865-웜홀/01865-웜홀-yeonju.py
  BOJ/bellman–ford/01865-웜홀/01865-웜홀-yoonbaek.py
  BOJ/bellman–ford/01865-웜홀/README.md
  BOJ/dp/01932-정수_삼각형/01932-정수_삼각형-jiwoong.py
  BOJ/dp/01932-정수_삼각형/01932-정수_삼각형-seokzin.py
  BOJ/dp/01932-정수_삼각형/01932-정수_삼각형-seungjoo.py
  BOJ/dp/01932-정수_삼각형/01932-정수_삼각형-seungkyu.py
  BOJ/dp/01932-정수_삼각형/01932-정수_삼각형-yeonhee.py
  BOJ/dp/01932-정수_삼각형/01932-정수_삼각형-yeonju.py
  BOJ/dp/01932-정수_삼각형/01932-정수_삼각형-yoonbaek.py
  BOJ/dp/01932-정수_삼각형/README.md
  BOJ/stack/01918-후위_표기식/01918-후위_표기식-jiwoong.py
  BOJ/stack/01918-후위_표기식/01918-후위_표기식-seokzin.py
  BOJ/stack/01918-후위_표기식/01918-후위_표기식-seungjoo.py
  BOJ/stack/01918-후위_표기식/01918-후위_표기식-seungkyu.py
  BOJ/stack/01918-후위_표기식/01918-후위_표기식-yeonhee.py
  BOJ/stack/01918-후위_표기식/01918-후위_표기식-yeonju.py
  BOJ/stack/01918-후위_표기식/01918-후위_표기식-yoonbaek.py
  BOJ/stack/01918-후위_표기식/README.md
Labels: 😅 할일

#170 21.12.05 (yeonju)
  BOJ/dijkstra/01753-최단경로/01753-최단경로-yeonju.py
  BOJ/mathematics/01629-곱셈/01629-곱셈-yeonju.py
Labels: 😀 위연주

#172 21.12.09 (seungjoo)
  BOJ/bellman–ford/01865-웜홀/01865-웜홀-seungjoo.py
  BOJ/dp/01932-정수_삼각형/01932-정수_삼각형-seungjoo.py
  BOJ/stack/01918-후위_표기식/01918-후위_표기식-seungjoo.py
Labels: 😀 한승주

#176 21.12.09 (seungkyu)
  BOJ/bellman–ford/01865-웜홀/01865-웜홀-seungkyu.py
  BOJ/dp/01932-정수_삼각형/01932-정수_삼각형-seungkyu.py
  BOJ/stack/01918-후위_표기식/01918-후위_표기식-seungkyu.py
Labels: :monkey_face: 김승규

#175 21.12.09 (seokzin)
  BOJ/bellman–ford/01865-웜홀/01865-웜홀-seokzin.py
  BOJ/dp/01932-정수_삼각형/01932-정수_삼각형-seokzin.py
  BOJ/stack/01918-후위_표기식/01918-후위_표기식-seokzin.py
Labels: 🌰 소석진

#174 21.12.09 (yeonhee)
  BOJ/bellman–ford/01865-웜홀/01865-웜홀-yeonhee.py
  BOJ/dp/01932-정수_삼각형/01932-정수_삼각형-yeonhee.py
  BOJ/stack/01918-후위_표기식/01918-후위_표기식-yeonhee.py
Labels: 🔮 채연희

#178 21.12.09 (yeonju)
  BOJ/bellman–ford/01865-웜홀/01865-웜홀-yeonju.py
  BOJ/dp/01932-정수_삼각형/01932-정수_삼각형-yeonju.py
  BOJ/stack/01918-후위_표기식/01918-후위_표기식-yeonju.py
Labels: 😀 위연주

#177 21.12.09 (yoonbaek)
  BOJ/dp/01932-정수_삼각형/01932-정수_삼각형-yoonbaek.go
  BOJ/dp/01932-정수_삼각형/01932-정수_삼각형-yoonbaek.py
  BOJ/stack/01918-후위_표기식/01918-후위_표기식-yoonbaek.go
  BOJ/stack/01918-후위_표기식/01918-후위_표기식-yoonbaek.py
Labels: 😀 백승윤

#184 21.12.12 (seungkyu)
  BOJ/bfs/02206-벽_부수고_이동하기/02206-벽_부수고_이동하기-seungkyu.py
  BOJ/dijkstra/01238-파티/01238-파티-seungkyu.py
Labels: :monkey_face: 김승규

#180 21.12.12 (seokzin)
  BOJ/bfs/02206-벽_부수고_이동하기/02206-벽_부수고_이동하기-seokzin.py
  BOJ/dijkstra/01238-파티/01238-파티-seokzin.py
Labels: 🌰 소석진

#186 21.12.12 (yeonhee)
  BOJ/bfs/02206-벽_부수고_이동하기/02206-벽_부수고_이동하기-yeonhee.py
  BOJ/dijkstra/01238-파티/01238-파티-yeonhee.py
Labels: 🔮 채연희

#181 21.12.12 (seungjoo)
  BOJ/bfs/02206-벽_부수고_이동하기/02206-벽_부수고_이동하기-seungjoo.py
  BOJ/dijkstra/01238-파티/01238-파티-seungjoo.py
Labels: 😀 한승주

#182 21.12.12 (yoonbaek)
  BOJ/bfs/02206-벽_부수고_이동하기/02206-벽_부수고_이동하기-yoonbaek.go
  BOJ/dijkstra/01238-파티/01238-파티-yoonbaek.go
Labels: 😀 백승윤

#183 21.12.12 (jiwoong)
  BOJ/bfs/02206-벽_부수고_이동하기/02206-벽_부수고_이동하기-jiwoong.py
  BOJ/dijkstra/01238-파티/01238-파티-jiwoong.py
Labels: 😀 정지웅

#190 21.12.16 (yeonhee)
  BOJ/divide_and_conquer/02263-트리의_순회/02263-트리의_순회-yeonhee.py
  BOJ/dp/09251-LCS/09251-LCS-yeonhee.py
Labels: 🔮 채연희

#191 21.12.16 (seungkyu)
  BOJ/divide_and_conquer/02263-트리의_순회/02263-트리의_순회-seungkyu.py
  BOJ/dp/09251-LCS/09251-LCS-seungkyu.py
Labels: :monkey_face: 김승규

#187 21.12.16 (seokzin)
  BOJ/divide_and_conquer/02263-트리의_순회/02263-트리의_순회-seokzin.py
  BOJ/divide_and_conquer/02263-트리의_순회/02263-트리의_순회-seokzin.ts
  BOJ/dp/09251-LCS/09251-LCS-seokzin.py
  BOJ/dp/09251-LCS/09251-LCS-seokzin.ts
  BOJ/mkdir.py
Labels: 🌰 소석진

#193 21.12.16 (jiwoong)
  BOJ/dp/09251-LCS/09251-LCS-jiwoong.py
Labels: 😀 정지웅

#188 21.12.16 (yoonbaek)
  BOJ/divide_and_conquer/02263-트리의_순회/02263-트리의_순회-yoonbaek.go
  BOJ/dp/09251-LCS/09251-LCS-yoonbaek.go
Labels: 😀 백승윤

#192 21.12.16 (yeonju)
  BOJ/divide_and_conquer/02263-트리의_순회/02263-트리의_순회-yeonju.py
  BOJ/dp/09251-LCS/09251-LCS-yeonju.py
Labels: 😀 위연주

#189 21.12.16 (seungjoo)
  BOJ/divide_and_conquer/02263-트리의_순회/02263-트리의_순회-seungjoo.py
  BOJ/dp/09251-LCS/09251-LCS-seungjoo.py
Labels: 😀 한승주

#194 21.12.19 Problem set
  BOJ/floyd–warshall/11404-플로이드/11404-플로이드-jiwoong.py
  BOJ/floyd–warshall/11404-플로이드/11404-플로이드-seokzin.ts
  BOJ/floyd–warshall/11404-플로이드/11404-플로이드-seungjoo.py
  BOJ/floyd–warshall/11404-플로이드/11404-플로이드-seungkyu.py
  BOJ/floyd–warshall/11404-플로이드/11404-플로이드-yeonhee.py
  BOJ/floyd–warshall/11404-플로이드/11404-플로이드-yeonju.py
  BOJ/floyd–warshall/11404-플로이드/11404-플로이드-yoonbaek.go
  BOJ/floyd–warshall/11404-플로이드/README.md
  BOJ/mathematics/11444-피보나치_수_6/11444-피보나치_수_6-jiwoong.py
  BOJ/mathematics/11444-피보나치_수_6/11444-피보나치_수_6-seokzin.ts
  BOJ/mathematics/11444-피보나치_수_6/11444-피보나치_수_6-seungjoo.py
  BOJ/mathematics/11444-피보나치_수_6/11444-피보나치_수_6-seungkyu.py
  BOJ/mathematics/11444-피보나치_수_6/11444-피보나치_수_6-yeonhee.py
  BOJ/mathematics/11444-피보나치_수_6/11444-피보나치_수_6-yeonju.py
  BOJ/mathematics/11444-피보나치_수_6/11444-피보나치_수_6-yoonbaek.go
  BOJ/mathematics/11444-피보나치_수_6/README.md
Labels: 😅 할일

#199 21.12.19 (yeonju)
  BOJ/divide_and_conquer/02263-트리의_순회/02263-트리의_순회-yeonju.py
  BOJ/floyd–warshall/11404-플로이드/11404-플로이드-yeonju.py
Labels: 😀 위연주

#196 21.12.19 (seungkyu)
  BOJ/floyd–warshall/11404-플로이드/11404-플로이드-seungkyu.py
  BOJ/mathematics/11444-피보나치_수_6/11444-피보나치_수_6-seungkyu.py
Labels: :monkey_face: 김승규

#197 21.12.19 (seokzin)
  BOJ/floyd–warshall/11404-플로이드/11404-플로이드-seokzin.ts
  BOJ/mathematics/11444-피보나치_수_6/11444-피보나치_수_6-seokzin.ts
Labels: 🌰 소석진

#200 21.12.19 (yeonhee)
  BOJ/floyd–warshall/11404-플로이드/11404-플로이드-yeonhee.py
  BOJ/mathematics/11444-피보나치_수_6/11444-피보나치_수_6-yeonhee.py
Labels: 🔮 채연희

#198 21.12.19 (seungjoo)
  BOJ/floyd–warshall/11404-플로이드/11404-플로이드-seungjoo.py
  BOJ/mathematics/11444-피보나치_수_6/11444-피보나치_수_6-seungjoo.py
Labels: 😀 한승주

#195 21.12.19 (yoonbaek)
  BOJ/floyd–warshall/11404-플로이드/11404-플로이드-yoonbaek.go
  BOJ/mathematics/11444-피보나치_수_6/11444-피보나치_수_6-yoonbaek.go
Labels: 😀 백승윤

#205 21.12.23 (seungkyu)
  BOJ/dp/11660-구간_합_구하기_5/11660-구간_합_구하기_5-seungkyu.py
  BOJ/dp/12865-평범한_배낭/12865-평범한_배낭-seungkyu.py
Labels: :monkey_face: 김승규

#206 21.12.23 (yoonbaek)
  BOJ/dp/11660-구간_합_구하기_5/11660-구간_합_구하기_5-yoonbaek.go
  BOJ/dp/12865-평범한_배낭/12865-평범한_배낭-yoonbaek.go
Labels: 😀 백승윤

#208 21.12.23 (yeonju)
  BOJ/dp/11660-구간_합_구하기_5/11660-구간_합_구하기_5-yeonju.py
  BOJ/dp/12865-평범한_배낭/12865-평범한_배낭-yeonju.py
Labels: 😀 위연주

#203 21.12.23 (seungjoo)
  BOJ/dp/11660-구간_합_구하기_5/11660-구간_합_구하기_5-seungjoo.py
  BOJ/dp/12865-평범한_배낭/12865-평범한_배낭-seungjoo.py
Labels: 😀 한승주

#209 21.12.23 (seokzin)
  BOJ/dp/11660-구간_합_구하기_5/11660-구간_합_구하기_5-seokzin.py
  BOJ/dp/11660-구간_합_구하기_5/11660-구간_합_구하기_5-seokzin.ts
  BOJ/dp/12865-평범한_배낭/12865-평범한_배낭-seokzin.py
  BOJ/dp/12865-평범한_배낭/12865-평범한_배낭-seokzin.ts
Labels: 🌰 소석진

#204 21.12.23 (jiwoong)
  BOJ/dp/11660-구간_합_구하기_5/11660-구간_합_구하기_5-jiwoong.py
  BOJ/dp/12865-평범한_배낭/12865-평범한_배낭-jiwoong.py
Labels: 😀 정지웅

#207 21.12.23 (yeonhee)
  BOJ/dp/11660-구간_합_구하기_5/11660-구간_합_구하기_5-yeonhee.py
  BOJ/dp/12865-평범한_배낭/12865-평범한_배낭-yeonhee.py
Labels: 🔮 채연희

#210 21.12.27 (yoonbaek)
  BOJ/bfs/16236-아기_상어/16236-아기_상어-yoonbaek.go
  BOJ/bfs/16236-아기_상어/16236-아기_상어-yoonbaek.py
Labels: 😀 백승윤
