Repository algo-itzy/algo-itzy, pull requests merged in 2021-10, with the labels that each got.

#60 21.10.03 (seokzin)
  BOJ/implementation/19238-스타트택시/19238-스타트택시-seokzin.py
  SWEA/divide_and_conquer/L5204-병합_정렬/L5204-병합_정렬-seokzin.py
  SWEA/divide_and_conquer/L5205-퀵_정렬/L5205-퀵_정렬-seokzin.py
  SWEA/divide_and_conquer/L5207-이진_탐색/L5207-이진_탐색-seokzin.py
Labels: 🌰 소석진

#61 21.10.03 (Jiwoong)
  BOJ/implementation/19238-스타트택시/19238-스타트택시-jiwoong.py
  SWEA/divide_and_conquer/L5204-병합_정렬/L5204-병합_정렬-jiwoong.py
  SWEA/divide_and_conquer/L5205-퀵_정렬/L5205-퀵_정렬-jiwoong.py
  SWEA/divide_and_conquer/L5207-이진_탐색/L5207-이진_탐색-jiwoong.py
Labels: 😀 정지웅

#64 21.10.07 Problem set
  BOJ/implementation/17135-캐슬_디펜스/17135-캐슬_디펜스-jiwoong.py
  BOJ/implementation/17135-캐슬_디펜스/17135-캐슬_디펜스-seokzin.py
  BOJ/implementation/17135-캐슬_디펜스/17135-캐슬_디펜스-seungjoo.py
  BOJ/implementation/17135-캐슬_디펜스/17135-캐슬_디펜스-seungkyu.py
  BOJ/implementation/17135-캐슬_디펜스/17135-캐슬_디펜스-yeonhee.py
  BOJ/implementation/17135-캐슬_디펜스/17135-캐슬_디펜스-yeonju.py
  BOJ/implementation/17135-캐슬_디펜스/17135-캐슬_디펜스-yoonbaek.py
  BOJ/implementation/17135-캐슬_디펜스/README.md
  SWEA/bfs/L5247-연산/L5247-연산-jiwoong.py
  SWEA/bfs/L5247-연산/L5247-연산-seokzin.py
  SWEA/bfs/L5247-연산/L5247-연산-seungjoo.py
  SWEA/bfs/L5247-연산/L5247-연산-seungkyu.py
  SWEA/bfs/L5247-연산/L5247-연산-yeonhee.py
  SWEA/bfs/L5247-연산/L5247-연산-yeonju.py
  SWEA/bfs/L5247-연산/L5247-연산-yoonbaek.py
  SWEA/bfs/L5247-연산/README.md
  SWEA/bfs/L5247-연산/input.txt
  SWEA/bfs/L5247-연산/output.txt
  SWEA/data_structure/L5248-그룹_나누기/L5248-그룹_나누기-jiwoong.py
  SWEA/data_structure/L5248-그룹_나누기/L5248-그룹_나누기-seokzin.py
  SWEA/data_structure/L5248-그룹_나누기/L5248-그룹_나누기-seungjoo.py
  SWEA/data_structure/L5248-그룹_나누기/L5248-그룹_나누기-seungkyu.py
  SWEA/data_structure/L5248-그룹_나누기/L5248-그룹_나누기-yeonhee.py
  SWEA/data_structure/L5248-그룹_나누기/L5248-그룹_나누기-yeonju.py
  SWEA/data_structure/L5248-그룹_나누기/L5248-그룹_나누기-yoonbaek.py
  SWEA/data_structure/L5248-그룹_나누기/README.md
  SWEA/data_structure/L5248-그룹_나누기/input.txt
  SWEA/data_structure/L5248-그룹_나누기/output.txt
  SWEA/dfs/L5208-전기버스2/L5208-전기버스2-jiwoong.py
  SWEA/dfs/L5208-전기버스2/L5208-전기버스2-seokzin.py
  SWEA/dfs/L5208-전기버스2/L5208-전기버스2-seungjoo.py
  SWEA/dfs/L5208-전기버스2/L5208-전기버스2-seungkyu.py
  SWEA/dfs/L5208-전기버스2/L5208-전기버스2-yeonhee.py
  SWEA/dfs/L5208-전기버스2/L5208-전기버스2-yeonju.py
  SWEA/dfs/L5208-전기버스2/L5208-전기버스2-yoonbaek.py
  SWEA/dfs/L5208-전기버스2/README.md
  SWEA/dfs/L5208-전기버스2/input.txt
  SWEA/dfs/L5208-전기버스2/output.txt
  SWEA/dfs/L5209-최소_생산_비용/L5209-최소_생산_비용-jiwoong.py
  SWEA/dfs/L5209-최소_생산_비용/L5209-최소_생산_비용-seokzin.py
  SWEA/dfs/L5209-최소_생산_비용/L5209-최소_생산_비용-seungjoo.py
  SWEA/dfs/L5209-최소_생산_비용/L5209-최소_생산_비용-seungkyu.py
  SWEA/dfs/L5209-최소_생산_비용/L5209-최소_생산_비용-yeonhee.py
  SWEA/dfs/L5209-최소_생산_비용/L5209-최소_생산_비용-yeonju.py
  SWEA/dfs/L5209-최소_생산_비용/L5209-최소_생산_비용-yoonbaek.py
  SWEA/dfs/L5209-최소_생산_비용/README.md
  SWEA/dfs/L5209-최소_생산_비용/input.txt
  SWEA/dfs/L5209-최소_생산_비용/output.txt
Labels: 😅 할일

#58 21.10.03 (seungjoo)
  BOJ/implementation/19238-스타트택시/19238-스타트택시-seungjoo.py
  SWEA/divide_and_conquer/L5204-병합_정렬/L5204-병합_정렬-seungjoo.py
  SWEA/divide_and_conquer/L5205-퀵_정렬/L5205-퀵_정렬-seungjoo.py
  SWEA/divide_and_conquer/L5207-이진_탐색/L5207-이진_탐색-seungjoo.py
Labels: 😀 한승주

#63 21.10.03 (yoonbaek)
  SWEA/divide_and_conquer/L5204-병합_정렬/L5204-병합_정렬-yoonbaek.py
  SWEA/divide_and_conquer/L5205-퀵_정렬/L5205-퀵_정렬-yoonbaek.py
  SWEA/divide_and_conquer/L5207-이진_탐색/L5207-이진_탐색-yoonbaek.py
Labels: 😀 백승윤, 😥 못풀었어요

#59 21.10.03 (yeonhee)
  BOJ/implementation/19238-스타트택시/19238-스타트택시-yeonhee.py
  SWEA/divide_and_conquer/L5204-병합_정렬/L5204-병합_정렬-yeonhee.py
  SWEA/divide_and_conquer/L5205-퀵_정렬/L5205-퀵_정렬-yeonhee.py
  SWEA/divide_and_conquer/L5207-이진_탐색/L5207-이진_탐색-yeonhee.py
Labels: 🔮 채연희, 😥 못풀었어요

#62 21.10.03 (seungkyu)
  SWEA/divide_and_conquer/L5204-병합_정렬/L5204-병합_정렬-seungkyu.py
  SWEA/divide_and_conquer/L5205-퀵_정렬/L5205-퀵_정렬-seungkyu.py
  SWEA/divide_and_conquer/L5207-이진_탐색/L5207-이진_탐색-seungkyu.py
Labels: :monkey_face: 김승규, 😥 못풀었어요

#108 21.10.31 (seokzin) 🎃
  Programmers/뉴스_클러스터링/뉴스_클러스터링-seokzin.py
  Programmers/캐시/캐시-seokzin.py
  Programmers/프렌즈4블록/프렌즈4블록-seokzin.py
Labels: 🌰 소석진

#109 21.10.31 (yeonhee) 🎃
  Programmers/뉴스_클러스터링/뉴스_클러스터링-yeonhee.py
  Programmers/캐시/캐시-yeonhee.py
  Programmers/프렌즈4블록/프렌즈4블록-yeonhee.py
Labels: 🔮 채연희

#113 21.10.31 (yoonbaek) 🎃
  Programmers/뉴스_클러스터링/뉴스_클러스터링-yoonbaek.py
  Programmers/캐시/캐시-yoonbaek.py
  Programmers/프렌즈4블록/프렌즈4블록-yoonbaek.py
Labels: 😀 백승윤

#111 21.10.31 (yeonju) 🎃
  Programmers/뉴스_클러스터링/뉴스_클러스터링-yeonju.py
  Programmers/캐시/캐시-yeonju.py
  Programmers/프렌즈4블록/프렌즈4블록-yeonju.py
Labels: 😀 위연주

#112 21.10.31 (seungkyu) 🎃
  Programmers/뉴스_클러스터링/뉴스_클러스터링-seungkyu.py
  Programmers/캐시/캐시-seungkyu.py
  Programmers/프렌즈4블록/프렌즈4블록-seungkyu.py
Labels: :monkey_face: 김승규

#110 21.10.31 (seungjoo) 🎃
  Programmers/뉴스_클러스터링/뉴스_클러스터링-seungjoo.py
  Programmers/캐시/캐시-seungjoo.py
  Programmers/프렌즈4블록/프렌즈4블록-seungjoo.py
Labels: 😀 한승주

#107 21.10.31 (jiwoong) 🎃
  Programmers/뉴스_클러스터링/뉴스_클러스터링-jiwoong.py
  Programmers/캐시/캐시-jiwoong.py
  Programmers/프렌즈4블록/프렌즈4블록-jiwoong.py
Labels: 😀 정지웅
