Repository algo-itzy/algo-itzy, pull requests merged in 2021-11, with the labels that each got.

#114 wip: Problem set (211014)
  Programmers/방금그곡/README.md
  Programmers/방금그곡/방금그곡-jiwoong.py
  Programmers/방금그곡/방금그곡-seokzin.py
  Programmers/방금그곡/방금그곡-seungjoo.py
  Programmers/방금그곡/방금그곡-seungkyu.py
  Programmers/방금그곡/방금그곡-yeonhee.py
  Programmers/방금그곡/방금그곡-yeonju.py
  Programmers/방금그곡/방금그곡-yoonbaek.py
  Programmers/압축/README.md
  Programmers/압축/압축-jiwoong.py
  Programmers/압축/압축-seokzin.py
  Programmers/압축/압축-seungjoo.py
  Programmers/압축/압축-seungkyu.py
  Programmers/압축/압축-yeonhee.py
  Programmers/압축/압축-yeonju.py
  Programmers/압축/압축-yoonbaek.py
Labels: 😅 할일

#116 21.11.04 (seokzin)
  Programmers/방금그곡/방금그곡-seokzin.py
  Programmers/압축/압축-seokzin.py
Labels: 🌰 소석진

#117 21.11.04 (jiwoong)
  Programmers/방금그곡/방금그곡-jiwoong.py
  Programmers/압축/압축-jiwoong.py
Labels: 😀 정지웅

#122 21.11.04 (yeonhee)
  Programmers/방금그곡/방금그곡-yeonhee.py
  Programmers/압축/압축-yeonhee.py
Labels: 🔮 채연희

#121 21.11.04 (yeonju)
  Programmers/방금그곡/방금그곡-yeonju.py
  Programmers/압축/압축-yeonju.py
Labels: 😀 위연주

#118 21.11.04 (seungkyu)
  Programmers/방금그곡/방금그곡-seungkyu.py
  Programmers/압축/압축-seungkyu.py
Labels: :monkey_face: 김승규

#120 21.11.04 (yoonbaek)
  Programmers/방금그곡/방금그곡-yoonbaek.py
  Programmers/압축/압축-yoonbaek.py
Labels: 😀 백승윤

#119 21.11.04 (seungjoo)
  Programmers/방금그곡/방금그곡-seungjoo.py
  Programmers/압축/압축-seungjoo.py
Labels: 😀 한승주

#124 21.11.07 (Jiwoong)
  Programmers/n진수_게임/n진수_게임-jiwoong.py
  Programmers/파일명_정렬/파일명_정렬-jiwoong.py
Labels: 😀 정지웅

#125 21.11.07 (seokzin)
  Programmers/n진수_게임/n진수_게임-seokzin.py
  Programmers/파일명_정렬/파일명_정렬-seokzin.py
Labels: 🌰 소석진

#126 21.11.07 (Yoonbaek)
  Programmers/n진수_게임/n진수_게임-yoonbaek.py
  Programmers/파일명_정렬/파일명_정렬-yoonbaek.py
Labels: 😀 백승윤

#128 21.11.07 (yeonju)
  Programmers/n진수_게임/n진수_게임-yeonju.py
  Programmers/파일명_정렬/파일명_정렬-yeonju.py
Labels: 😀 위연주

#127 21.11.07 (seungjoo)
  Programmers/n진수_게임/n진수_게임-seungjoo.py
  Programmers/파일명_정렬/파일명_정렬-seungjoo.py
Labels: 😀 한승주

#129 21.11.14 Problem set
  Programmers/거리두기_확인하기/README.md
  Programmers/거리두기_확인하기/거리두기_확인하기-jiwoong.py
  Programmers/거리두기_확인하기/거리두기_확인하기-seokzin.py
  Programmers/거리두기_확인하기/거리두기_확인하기-seungjoo.py
  Programmers/거리두기_확인하기/거리두기_확인하기-seungkyu.py
  Programmers/거리두기_확인하기/거리두기_확인하기-yeonhee.py
  Programmers/거리두기_확인하기/거리두기_확인하기-yeonju.py
  Programmers/거리두기_확인하기/거리두기_확인하기-yoonbaek.py
  Programmers/표_편집/README.md
  Programmers/표_편집/표_편집-jiwoong.py
  Programmers/표_편집/표_편집-seokzin.py
  Programmers/표_편집/표_편집-seungjoo.py
  Programmers/표_편집/표_편집-seungkyu.py
  Programmers/표_편집/표_편집-yeonhee.py
  Programmers/표_편집/표_편집-yeonju.py
  Programmers/표_편집/표_편집-yoonbaek.py
Labels: 😅 할일

#132 21.11.14 (jiwoong)
  Programmers/거리두기_확인하기/거리두기_확인하기-jiwoong.py
  Programmers/표_편집/표_편집-jiwoong.py
Labels: 😀 정지웅

#131 21.11.14 (yoonbaek)
  Programmers/거리두기_확인하기/거리두기_확인하기-yoonbaek.py
  Programmers/표_편집/표_편집-yoonbaek.py
Labels: 😀 백승윤

#136 21.11.14 (seungkyu)
  Programmers/거리두기_확인하기/거리두기_확인하기-seungkyu.py
Labels: :monkey_face: 김승규

#134 21.11.14 (yeonhee)
  Programmers/거리두기_확인하기/거리두기_확인하기-yeonhee.py
  Programmers/표_편집/표_편집-yeonhee.py
Labels: 🔮 채연희

#133 21.11.14 (seokzin)
  Programmers/거리두기_확인하기/거리두기_확인하기-seokzin.py
  Programmers/표_편집/표_편집-seokzin.py
Labels: 🌰 소석진

#135 21.11.14 (seungjoo)
  Programmers/거리두기_확인하기/거리두기_확인하기-seungjoo.py
  Programmers/표_편집/표_편집-seungjoo.py
Labels: 😀 한승주

#138 21.11.18 (seokzin)
  BOJ/bruteforcing/09663-N-Queen/09663-N-Queen-seokzin.py
Labels: 🌰 소석진

#139 21.11.18 (yeonhee)
  BOJ/bruteforcing/09663-N-Queen/09663-N-Queen-yeonhee.py
Labels: 🔮 채연희

#142 21.11.18 (jiwoong)
  BOJ/bruteforcing/09663-N-Queen/09663-N-Queen-jiwoong.py
Labels: 😀 정지웅

#140 21.11.18 (yeonju)
  BOJ/bruteforcing/09663-N-Queen/09663-N-Queen-yeonju.py
Labels: 😀 위연주

#141 21.11.18 (seungjoo)
  BOJ/bruteforcing/09663-N-Queen/09663-N-Queen-seungjoo.py
Labels: 😀 한승주

#143 21.11.21 (seokzin)
  BOJ/dp/11053-가장_긴_증가하는_부분_수열/11053-가장_긴_증가하는_부분_수열-seokzin.py
Labels: 🌰 소석진

#147 21.11.21 (jiwoong)
  BOJ/dp/11053-가장_긴_증가하는_부분_수열/11053-가장_긴_증가하는_부분_수열-jiwoong.py
Labels: 😀 정지웅

#145 21.11.21 (seungkyu)
  BOJ/dp/11053-가장_긴_증가하는_부분_수열/11053-가장_긴_증가하는_부분_수열-seungkyu.py
Labels: :monkey_face: 김승규

#146 21.11.21 (yeonhee)
  BOJ/dp/11053-가장_긴_증가하는_부분_수열/11053-가장_긴_증가하는_부분_수열-yeonhee.py
Labels: 🔮 채연희

#148 21.11.21 (yoonbaek)
  BOJ/dp/11053-가장_긴_증가하는_부분_수열/11053-가장_긴_증가하는_부분_수열-yoonbaek.py
Labels: 😀 백승윤

#149 21.11.21 (yeonju)
  BOJ/dp/11053-가장_긴_증가하는_부분_수열/11053-가장_긴_증가하는_부분_수열-yeonju.py
Labels: 😀 위연주

#144 21.11.21 (seungjoo)
  BOJ/dp/11053-가장_긴_증가하는_부분_수열/11053-가장_긴_증가하는_부분_수열-seungjoo.py
Labels: 😀 한승주

#151 21.11.28 (jiwoong)
  BOJ/bfs/13549-숨바꼭질_3/13549-숨바꼭질_3-jiwoong.py
Labels: 😀 정지웅

#152 21.11.28 (seokzin)
  BOJ/bfs/13549-숨바꼭질_3/13549-숨바꼭질_3-seokzin.py
  BOJ/dfs/15650-N과_M_(2)/15650-N과_M_(2)-seokzin.py
Labels: 🌰 소석진

#153 21.11.28 (seungjoo)
  BOJ/bfs/13549-숨바꼭질_3/13549-숨바꼭질_3-seungjoo.py
  BOJ/dfs/15650-N과_M_(2)/15650-N과_M_(2)-seungjoo.py
Labels: 😀 한승주

#155 21.11.28 (seungkyu)
  BOJ/bfs/13549-숨바꼭질_3/13549-숨바꼭질_3-seungkyu.py
  BOJ/dfs/15650-N과_M_(2)/15650-N과_M_(2)-seungkyu.py
Labels: :monkey_face: 김승규

#154 21.11.28 (jiwoong)
  BOJ/dfs/15650-N과_M_(2)/15650-N과_M_(2)-jiwoong.py
Labels: 😀 정지웅
