Repository algo-itzy/algo-itzy, pull requests merged in 2022-01, with the labels that each got.

#213 21.01.06 (yoonbaek)
  BOJ/binary_search/02295-세_수의_합/02295-세_수의_합-yoonbaek.go
Labels: 😀 백승윤

#212 21.01.06 (seungkyu)
  BOJ/binary_search/02295-세_수의_합/02295-세_수의_합-seungkyu.py
  BOJ/implementation/12100-2048_(Easy)/12100-2048_(Easy)-seungkyu.py
Labels: :monkey_face: 김승규

#216 22.01.09 Problem set
  BOJ/implementation/20061-모노미노도미노2/20061-모노미노도미노2-jiwoong.py
  BOJ/implementation/20061-모노미노도미노2/20061-모노미노도미노2-seokzin.ts
  BOJ/implementation/20061-모노미노도미노2/20061-모노미노도미노2-seungjoo.py
  BOJ/implementation/20061-모노미노도미노2/20061-모노미노도미노2-seungkyu.py
  BOJ/implementation/20061-모노미노도미노2/20061-모노미노도미노2-yeonhee.py
  BOJ/implementation/20061-모노미노도미노2/20061-모노미노도미노2-yeonju.py
  BOJ/implementation/20061-모노미노도미노2/20061-모노미노도미노2-yoonbaek.go
  BOJ/implementation/20061-모노미노도미노2/README.md
Labels: 😅 할일

#214 22.01.06 (seungjoo)
  BOJ/binary_search/02295-세_수의_합/02295-세_수의_합-seungjoo.py
  BOJ/implementation/12100-2048_(Easy)/12100-2048_(Easy)-seungjoo.py
Labels: 😀 한승주

#218 21.01.09 (jiwoong)
  BOJ/implementation/20061-모노미노도미노2/20061-모노미노도미노2-jiwoong.py
Labels: 😀 정지웅

#219 22.01.02 Problem set
  BOJ/binary_search/02003-수들의_합_2/02003-수들의_합_2-jiwoong.py
  BOJ/binary_search/02003-수들의_합_2/02003-수들의_합_2-seokzin.ts
  BOJ/binary_search/02003-수들의_합_2/02003-수들의_합_2-seungjoo.py
  BOJ/binary_search/02003-수들의_합_2/02003-수들의_합_2-seungkyu.py
  BOJ/binary_search/02003-수들의_합_2/02003-수들의_합_2-yeonhee.py
  BOJ/binary_search/02003-수들의_합_2/02003-수들의_합_2-yeonju.py
  BOJ/binary_search/02003-수들의_합_2/02003-수들의_합_2-yoonbaek.go
  BOJ/binary_search/02003-수들의_합_2/README.md
  BOJ/implementation/17143-낚시왕/17143-낚시왕-jiwoong.py
  BOJ/implementation/17143-낚시왕/17143-낚시왕-seokzin.ts
  BOJ/implementation/17143-낚시왕/17143-낚시왕-seungjoo.py
  BOJ/implementation/17143-낚시왕/17143-낚시왕-seungkyu.py
  BOJ/implementation/17143-낚시왕/17143-낚시왕-yeonhee.py
  BOJ/implementation/17143-낚시왕/17143-낚시왕-yeonju.py
  BOJ/implementation/17143-낚시왕/17143-낚시왕-yoonbaek.go
  BOJ/implementation/17143-낚시왕/README.md
Labels: 😅 할일

#217 21.01.09 (seungjoo)
  BOJ/implementation/20061-모노미노도미노2/20061-모노미노도미노2-seungjoo.py
Labels: 😀 한승주

#223 22.01.16 Problem set
  BOJ/implementation/17779-게리멘더링2/17779-게리멘더링2-jiwoong.py
  BOJ/implementation/17779-게리멘더링2/17779-게리멘더링2-seokzin.ts
  BOJ/implementation/17779-게리멘더링2/17779-게리멘더링2-seungjoo.py
  BOJ/implementation/17779-게리멘더링2/17779-게리멘더링2-seungkyu.py
  BOJ/implementation/17779-게리멘더링2/17779-게리멘더링2-yeonhee.py
  BOJ/implementation/17779-게리멘더링2/17779-게리멘더링2-yeonju.py
  BOJ/implementation/17779-게리멘더링2/17779-게리멘더링2-yoonbaek.go
  BOJ/implementation/17779-게리멘더링2/README.md
Labels: 😅 할일

#220 22.01.13 (seungjoo)
  BOJ/binary_search/02003-수들의_합_2/02003-수들의_합_2-seungjoo.py
  BOJ/implementation/17143-낚시왕/17143-낚시왕-seungjoo.py
Labels: 😀 한승주

#221 22.01.13 (yeonhee)
  BOJ/binary_search/02003-수들의_합_2/02003-수들의_합_2-yeonhee.py
Labels: 🔮 채연희

#224 22.01.16 (seungjoo)
  BOJ/implementation/17779-게리멘더링2/17779-게리멘더링2-seungjoo.py
Labels: 😀 한승주

#225 21.01.16 (yoonbaek)
  BOJ/implementation/17779-게리멘더링2/17779-게리멘더링2-yoonbaek.go
Labels: 😀 백승윤

#222 22.01.13 (jiwoong)
  BOJ/binary_search/02003-수들의_합_2/02003-수들의_합_2-jiwoong.py
Labels: 😀 정지웅

#228 21.01.20 (yoonbaek)
  BOJ/binary_search/18869-멀티버스2/18869-멀티버스2-yoonbaek.go
Labels: 😀 백승윤

#227 22.01.20 (jiwoong)
  BOJ/binary_search/18869-멀티버스2/18869-멀티버스2-jiwoong.py
Labels: 😀 정지웅

#230 22.01.27 (seungkyu)
  BOJ/implementation/21610-마법사_상어와_비바라기/21610-마법사_상어와_비바라기-seungkyu.py
Labels: :monkey_face: 김승규
